name: Build exe with Pyinstaller

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build exe
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: high-score-get
        path: dist/windows

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/windows/high-score-get.*"
        token: ${{ secrets.GH_TOKEN }}
        commit: ${GITHUB_SHA}
        tag: ${GITHUB_SHA}