name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (overrides push tag)'
        required: false
        default: ''

jobs:
  build:
    name: Build, Zip & Bundle Artifacts
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt pyinstaller filedate

      - name: Build executable with PyInstaller
        working-directory: src
        shell: pwsh
        run: |
          pyinstaller --noconfirm --clean --onefile `
            --name vpc-get-high-scores-image `
            createHighScoreImage.py

      - name: Prepare release folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release
          Copy-Item -Path src\dist\vpc-get-high-scores-image.exe `
                    -Destination release\
          Copy-Item -Path src\POPMENU_GetHighScoresForAllTables.bat `
                    -Destination release\
          Copy-Item -Path src\playsound.exe `
                    -Destination release\
          Copy-Item -Path src\UpdateHighScoreStart.mp3 `
                    -Destination release\
          Copy-Item -Path src\UpdateHighScoreStop.mp3 `
                    -Destination release\

      - name: Zip all release files
        run: |
          Compress-Archive -Path release\* -DestinationPath release.zip -Force

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: release.zip

  release:
    name: Create Release & Attach ZIP
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v4
        with:
          name: release-zip
          path: artifact

      - name: Determine release tag
        id: tagger
        run: |
          if [ -n "${{ github.event.inputs.release_tag }}" ]; then
            echo "tag=${{ github.event.inputs.release_tag }}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          else
            echo "tag=unreleased-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: Release ${{ steps.tagger.outputs.tag }}
          body: |
            Auto-generated release for ${{ steps.tagger.outputs.tag }}
            See CHANGELOG.md for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Upload ZIP asset to release
        run: |
          gh release upload \
            ${{ steps.tagger.outputs.tag }} \
            artifact/release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
